name: run unit tests of feature branches 
on: 
  push: 
    branches: 
         "features/*"

jobs: 
  run-unit-tests: 
     runs-on : windows-latest 
     steps: 
         - name: Checkout
           uses: actions/checkout@v3.3.0

         - name: run unit test 
           run: mvn test

